### ISSUE TITLE
Compilation on Linux

### ISSUE THREAD

**Issue by mc-17** [jief666/hdimount#5]
Thank you for making this! It works great with lzfse, unlike darling-dmg.

Do you have a list of requirements, and ideally also a makefile? I am eager to contribute, but am currently unable to compile it.

**Comment by jief666** [comment]
There is a makefile in build_release_linux-gcc-openssl_hdimount. It's the makefile generated by Eclipse, but it should work outside eclipse.
Can you try and tell me ?

**Comment by mc-17** [comment]
> There is a makefile in build_release_linux-gcc-openssl_hdimount. It's the makefile generated by Eclipse, but it should work outside eclipse.
> Can you try and tell me ?

Apologies! I missed this directory entirely somehow.

Still working on getting libxml includes sorted on Manjaro, but the only thing I've need to change sofar is `linux-gcc` and `linux-g++` to `gcc` and `g++`. Thanks!

**Comment by jief666** [comment]
Yes. To not have to do that, you can use the script in "tools/scripts/build_hdimount".

**Comment by jief666** [comment]
If you'd like to contribute, you may consider using eclipse and cdt...
